# Generated by Django 3.1.2 on 2020-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
